image: alpine/latest
packages:
  - nodejs
  - npm
sources:
  - https://git.sr.ht/~rasch/deadlift-png
environment:
  project: deadlift-png
secrets:
  - ac7323fc-d1fd-4005-97fb-a8c058a0dc6f # NPM publish token
tasks:
  - setup: |
      sudo npm install --global pnpm
      cd "$project"
      pnpm install
  - lint: |
      cd "$project"
      pnpm run lint
  - test: |
      cd "$project"
      pnpm run --silent test
  - stop_if_not_release: |
      cd "$project"
      git describe --exact-match HEAD || complete-build
  - release: |
      cd "$project"
      pnpm run build
      echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
      set +x
      . ~/.env
      set -x
      npm publish --access public
